#+TITLE: Generic Workflow for Migrating Files into org-mode Outline

* Summary

Many development tools provide code generation utilities for quickly creating the files and directories used by developers. This document will provide a generic workflow to migrate the existing files into an =org-mode= outline where the contents of the external files will be maintained using the Literate Programming paradigm.

* Migration Workflow

** Create a dedicated =org-mode= file

For this example, let's use the [[common-project-files.org]] as the dedicated =org-mode= file.

** Create a list of files that will migrated into dedicated =org-mode= file

The list of files should be added as a named table or generated automatically as results from a named code block.

  - For example, the org syntax for a table named =file-list-table= which contains =.gitignore=, =LICENSE=, and =README.org=.
    
    #+NAME: create-file-list-table
    #+BEGIN_SRC org :exports code :results drawer replace 
      ,#+NAME: file-list-table
      | Files      |
      |------------|
      | README.org |
      | .gitignore |
      | LICENSE    |
   #+END_SRC

   #+BEGIN_QUOTE
     *Note:* Using the ~#+NAME:~ syntax will allow table data or the results from a =src= block to be used as input for an automated workflow if available.
   #+END_QUOTE

** Create dedicated =src= block for each file in the list of files under a =org-mode= header as needed.

*** Repeat the workflow below for each file

1. Create a dedicated parent heading (Optional)

   In some uses cases, grouping multiple project files under a dedicated heading will improve the readability and allow readers to quickly navigate to a specific group of files. 

   - If the dedicated parent heading is needed, then:

     - Validate the dedicated heading exists. 

       - Create the dedicated heading if the heading does not exist.

     - Navigate to the section directly under dedicated heading.

2. Create dedicated subheading for each filename (Optional) 

   In some uses cases, providing a dedicated subheading will improve the readability and allow readers to quickly navigate to a specific filename. 

   - If a dedicated subheading is provided, then:

     - Validate the dedicated subheading exists. 

       - Create the dedicated subheading if the subheading does not exist.

     - Navigate to the section directly under dedicated subheading.

3. Create a dedicated =src= block for the file.

   The dedicated =src= block should implement the following syntax:

   - Assigned human readible name.  

     For example, if the filename was =README.org= then using the filename as the assigned name would be appropriate.

     #+BEGIN_SRC org :exports code :eval never
       ,#+NAME: README.org
       # Start of SRC Code Block for README.org file ...
     #+END_SRC

     #+BEGIN_QUOTE
       *Note:* The syntax for ~#+NAME:~ does not allow whitespace characters. If the filename contains any whitespaces, e.g. =Updates List.txt=, then assign the block another name, e.g. =updates-list-txt=.
     #+END_QUOTE

   - Designate a language that is compatible with the contents of the file.

     For example:

     - If the file is a source code file, designate the lanuage of code block by file extension or type, i.e. =.rb= \rightarrow ruby, =.el= \rightarrow elisp, =.sh= \rightarrow shell, etc\dots  

     - If the file is a text file, designate =org= or =css= as the language of the code block.

   - Add the ~:tangle~ header with the path to the file, e.g. =README.org=, to the headers of the =src= block.

     #+BEGIN_SRC org :exports code :eval never 
       ,#+BEGIN_SRC org :tangle README.org 
       ,#+END_SRC
     #+END_SRC

4. Open the =src= block using ~C-c '~ which invokes ~org-edit-special~ function.

5. Insert the file contents into the =src= block using ~C-x i~ key chord which invokes the ~insert-file~ function.

6. Close the =src= block using ~C-c '~ which invokes ~org-edit-special~ function.

     #+BEGIN_SRC org :exports code :eval never 
       ,#+BEGIN_SRC org :tangle README.org 
         Contents of README.org file will go here ...
       ,#+END_SRC
     #+END_SRC

7. Confirm the original file, e.g. =README.org=, is backed up in version control. 

8. Tangle the =src= block contents into the original file using ~C-c~ ~C-v~ ~t~ which invokes the ~org-babel-tangle~ function.

9. Use version control to validate that the contents original are unchanged.

   If the contents of the original file are not the same, troubleshoot the migration steps. The most common reason is that a blank line was unintentionally added or deleted while inserting the file contents into the =src= block.   

*** Migration Workflow Automation                                :noexport:

For this example, we'll use a named =src= block written in =elisp=. In practice, I encourage you to use the language you prefer. To date, there are over 30 supported programming languages.

#+BEGIN_SRC org :exports code :results drawer replace :eval never 

  ,#+NAME: process-files-into-org-syntax
  ,#+BEGIN_SRC elisp :var files=file-list-table
    files
  ,#+END_SRC


#+END_SRC

#+RESULTS:
:RESULTS:

#+NAME: ldo/process-files-into-org-syntax
#+BEGIN_SRC elisp :var files=file-list-table :results replace output 
  (defun ldo/process-files-into-org-syntax (files-list)
    "Process list of files into org-mode syntax"
    (dolist (filename files-list)
      (print (format "%s" (car filename)))
     )
    )

  (process-files-into-org-syntax files)
#+END_SRC

#+RESULTS: ldo/process-files-into-org-syntax
: 
: ".gitignore"
: 
: "LICENSE"
: 
: "README.org"

:END:

- Code Functionality ::

 - If the =src= block is empty, insert the contents of the file into the block. 

   #+BEGIN_QUOTE
     *Note:* The contents of the file should be escaped as specified in the [[https://orgmode.org/worg/dev/org-syntax.html][Org Syntax (draft)]] specification.
   #+END_QUOTE

* Export Settings                                                  :noexport:

#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:{} arch:headline
#+OPTIONS: author:nil broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:nil todo:t |:t

#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport

#
# Add Fix for org-ruby support
#

#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport


